# Generated by Django 5.0.6 on 2026-05-07 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='attachment',
            new_name='attachments_related_ac8375_idx',
            old_name='attachment_related_dbcbb8_idx',
        ),
    ]
