# Generated by Django 5.0.6 on 2026-05-07 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='expense',
            new_name='finance_exp_project_68b695_idx',
            old_name='finance_exp_project_1d7dc7_idx',
        ),
        migrations.RenameIndex(
            model_name='expense',
            new_name='finance_exp_approva_a49c16_idx',
            old_name='finance_exp_approva_f0da3e_idx',
        ),
        migrations.RenameIndex(
            model_name='expense',
            new_name='finance_exp_payment_ed1aa1_idx',
            old_name='finance_exp_payment_b50183_idx',
        ),
    ]
